// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 002_truncateUsers.sql

package database

import (
	"context"
)

const truncateUsers = `-- name: truncateUsers :exec
TRUNCATE TABLE users
`

func (q *Queries) TruncateUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateUsers)
	return err
}
