// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 003_truncateChirps.sql

package database

import (
	"context"
)

const truncateChirps = `-- name: TruncateChirps :exec
TRUNCATE TABLE chirps RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateChirps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateChirps)
	return err
}
